In [4]:
import numpy as np

n = np.array([123,232])

def ndfunc(ntemp):
    print("Data type = {0}".format(ntemp.dtype))
    print("Np. of Dimentions = {0}".format(ntemp.ndim))
    print("Size = {0}".format(ntemp.size))
    print("Shape = {0}".format(ntemp.shape))

ndfunc(n)

Data type = int32
Np. of Dimentions = 1
Size = 2
Shape = (2,)


In [5]:
#arange returns an array
#range doesnt return anything

# dont use loops while using numpy because it has already compiled code

#### Rules: 1. Always use Ufuncs. 2. Functions that give stats about the array which is called aggrigation. 3. Broadcasting Doing operations on arrays that of different types or sizes
##### 4. Fancy indexing
### Keep utilizing the performance by not using for loops

# 

In [8]:
x = np.arange(0,1,0.1)
ndfunc(x)

Data type = float64
Np. of Dimentions = 1
Size = 10
Shape = (10,)


In [10]:
n1 = np.ones(20)
#print(n1)
n2 = n1.reshape(4,5)
#print(n2)
ndfunc(n1)
ndfunc(n2)

Data type = float64
Np. of Dimentions = 1
Size = 20
Shape = (20,)
Data type = float64
Np. of Dimentions = 2
Size = 20
Shape = (4, 5)


In [11]:
n3 = n1.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [14]:
n = np.ones(162).reshape(6,3,9)
#m = np.ones(162).reshape(3,3,2,3,3)
print(n)
ndfunc(n)
#ndfunc(m)
#right most is the columns, next is rows, then blocks of 6 rows... CRBBBBBB

[[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]]
Data type = float64
Np. of Dimentions = 3
Size = 162
Shape = (6, 3, 9)


In [ ]:
## HW is to timeit all the