In [4]:
import numpy as np

n = np.array([123,232])

def ndfunc(ntemp):
    print("Data type = {0}".format(ntemp.dtype))
    print("Np. of Dimentions = {0}".format(ntemp.ndim))
    print("Size = {0}".format(ntemp.size))
    print("Shape = {0}".format(ntemp.shape))

ndfunc(n)

Data type = int32
Np. of Dimentions = 1
Size = 2
Shape = (2,)


In [5]:
#arange returns an array
#range doesnt return anything

# dont use loops while using numpy because it has already compiled code

#### Rules: 1. Always use Ufuncs. 2. Functions that give stats about the array which is called aggrigation. 3. Broadcasting Doing operations on arrays that of different types or sizes
##### 4. Fancy indexing
### Keep utilizing the performance by not using for loops

# In ufuncs: arthematic, comparision, logorithmic, max,min

In [8]:
x = np.arange(0,1,0.1)
ndfunc(x)

Data type = float64
Np. of Dimentions = 1
Size = 10
Shape = (10,)


In [10]:
n1 = np.ones(20)
#print(n1)
n2 = n1.reshape(4,5)
#print(n2)
ndfunc(n1)
ndfunc(n2)

Data type = float64
Np. of Dimentions = 1
Size = 20
Shape = (20,)
Data type = float64
Np. of Dimentions = 2
Size = 20
Shape = (4, 5)


In [11]:
n3 = n1.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [14]:
n = np.ones(162).reshape(6,3,9)
#m = np.ones(162).reshape(3,3,2,3,3)
print(n)
ndfunc(n)
#ndfunc(m)
#right most is the columns, next is rows, then blocks of 6 rows... CRBBBBBB

[[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]]
Data type = float64
Np. of Dimentions = 3
Size = 162
Shape = (6, 3, 9)


In [15]:
## HW is to timeit all the operations and cos^2x and sin^2x = 1 with lists and numpy arrays

In [12]:
# calculate the nearest neighbour for any point

import numpy as np
import math


def dist(x1,x2,y1,y2):
    dist = (x2 - x1)*(x2 - x1) + (y2 - y1)*(y2 - y1)

    return math.sqrt(dist)


#l = [i for i in range(20,30)]
#li = [i for i in range(50,60)]

#for i in range(9):
 #   print(dist(0,l[i],0,li[i]))

#li = [i for i in range(1,11)]

#l = [j for j in range(20,30)]   

xcord = np.random.randint(10, size=(10))

ycord = np.random.randint(10, size=(10))


for j in range(10):
    pox = xcord[j]
    poy = ycord[j]

    minn = np.finfo(np.float64).max

    for i in range(10):
        #print(pox,xcord[i],poy,ycord[i])
        k = dist(pox,xcord[i],poy,ycord[i])
        #print(k) 
        if minn > k and k != 0:
            minn = k
    print(minn)
xcord


1.0
1.4142135623730951
1.0
3.0
3.605551275463989
3.0
1.0
2.8284271247461903
1.4142135623730951
1.0


array([1, 4, 3, 8, 4, 8, 1, 7, 5, 3])

In [57]:
#x = np.random.random_sample((2,3,2))
#print(x)
x = np.random.rand(1,2,2)
print(x)

[[[ 0.68103929  0.23783143]
  [ 0.42394413  0.57347405]]]


In [71]:
dist(1,20,1,20)

26.870057685088806

In [73]:
dist(1,20,1,20)

26.870057685088806

In [75]:
dist(1,30,1,30)

41.012193308819754

In [143]:
x = np.random.randint(10, size=(10))
x

array([8, 9, 9, 8, 4, 5, 6, 8, 8, 2])

In [166]:
#a = np.max
#type(a)
a = np.finfo(np.float64).max
print(a)
b = np.iinfo(np.int32).max
b

1.79769313486e+308


2147483647

In [6]:
import numpy as np
#15/1/19

### Broadcasting

a = np.zeros((3,3))
b = np.arange(3)
print(b.shape)
print(a.shape)
print(b.ndim)

# repeatation starts from RHS


(3,)
(3, 3)
1


In [18]:
a1 = a + 1
a2 = a1 + 1 
print(a1)
print(a2)

a1 - a2 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])